# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
version: 2

updates:
  # 1. GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: &weekly-checkout
      interval: "weekly"
      day: "sunday"
      time: "04:00"
    open-pull-requests-limit: 1
    groups:
      actions-dependencies:
        patterns: ["*"]

  # 2. NPM (Web dependencies)
  - package-ecosystem: "npm"
    directory: "/"
    schedule: *weekly-checkout
    open-pull-requests-limit: 1
    groups:
      npm-dependencies:
        patterns: ["*"]

  # 3. Pip (Python dependencies)
  - package-ecosystem: "pip"
    directory: "/"
    schedule: *weekly-checkout
    open-pull-requests-limit: 1
    groups:
      python-dependencies:
        patterns: ["*"]
